### ISSUE TITLE
Sometimes samplesets are stored as valid but marked as invalid or vice versa

### ISSUE THREAD

**Issue by dionyziz** [decrypto-org/rupture#340]

**Comment by dimkarakostas** [comment]
Example error log:

Internal Server Error: /breach/work_completed/6
Traceback (most recent call last):
  File "/home/dimitris/workspace/rupture/backend/env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/dimitris/workspace/rupture/backend/env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/dimitris/workspace/rupture/backend/env/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/dimitris/workspace/rupture/backend/breach/views.py", line 38, in work_completed
    victory = strategy.work_completed(success)
  File "/home/dimitris/workspace/rupture/backend/breach/strategy.py", line 495, in work_completed
    self._analyze_current_round()
  File "/home/dimitris/workspace/rupture/backend/breach/strategy.py", line 259, in _analyze_current_round
    self._decision = decide_next_world_state(current_round_samplesets)
  File "/home/dimitris/workspace/rupture/backend/breach/analyzer.py", line 105, in decide_next_world_state
    assert(count == samplesets_per_candidate)
AssertionError
[24/Feb/2017 12:03:46] "POST /breach/work_completed/6 HTTP/1.1" 500 96532
[24/Feb/2017 12:03:57] DEBUG [breach.strategy:193] Found 0 unstarted samplesets
Internal Server Error: /breach/get_work/6
Traceback (most recent call last):
  File "/home/dimitris/workspace/rupture/backend/env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/dimitris/workspace/rupture/backend/env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/dimitris/workspace/rupture/backend/breach/views.py", line 18, in get_work
    new_work = strategy.get_work()
  File "/home/dimitris/workspace/rupture/backend/breach/strategy.py", line 195, in get_work
    assert(unstarted_samplesets)
AssertionError
[24/Feb/2017 12:03:58] "GET /breach/get_work/6 HTTP/1.1" 500 74598
[24/Feb/2017 12:04:08] WARNING [breach.strategy:172] Caught 409 while trying to start sniffer.
[24/Feb/2017 12:04:08] "GET /breach/get_work/6 HTTP/1.1" 200 2
[24/Feb/2017 12:04:18] DEBUG [breach.strategy:193] Found 0 unstarted samplesets
Internal Server Error: /breach/get_work/6
Traceback (most recent call last):
  File "/home/dimitris/workspace/rupture/backend/env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/dimitris/workspace/rupture/backend/env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/dimitris/workspace/rupture/backend/breach/views.py", line 18, in get_work
    new_work = strategy.get_work()
  File "/home/dimitris/workspace/rupture/backend/breach/strategy.py", line 195, in get_work
    assert(unstarted_samplesets)
AssertionError
[24/Feb/2017 12:04:18] "GET /breach/get_work/6 HTTP/1.1" 500 74598
[24/Feb/2017 12:04:29] WARNING [breach.strategy:172] Caught 409 while trying to start sniffer.
[24/Feb/2017 12:04:39] "GET /breach/get_work/6 HTTP/1.1" 200 2
[24/Feb/2017 12:04:49] DEBUG [breach.strategy:193] Found 0 unstarted samplesets
